print()
print()
print("                             -:                                      o.                             ")
print("                             `h+       :yhhhhhhhhddddhhhhhhy/       sh                              ")
print("                              `do     yMMMMMMMMMMMMMMMMMMMMMMh    `yd`                              ")
print("                               .ms    hMMMMMMMMMMMMMMMMMMMMMMm   `hm`                               ")
print(" os/`                           .Ny`  dMMMMMMMMMMMMMMMMMMMMMMm  `dN.                           `:ss`")
print("  .sNho-                         -Nh` dMMMMMMMMMMMMMMMMMMMMMMd `dN-                         .+hNy-  ")
print("    `omMmy/`                      :Nd`hMMMMMMMMMMMMMMMMMMMMMMd.mN:                      `:smMNs.    ")
print("       /dMMMdo-                    /Md/NMMMhddddddddddddhMMMNomM/                    .+hMMMm+`      ")
print("         :hMMMMmy/`              :ydsMm/mMM+MMMMMMMMMMMMoMMN+NM+hh/`             `:smMMMMd/         ")
print("           .sNMMMMMdo-        .oNMMMmsMN/mM+MMMMMMMMMMMMoMm+NMohMMMNy-        .+hMMMMMMy-           ")
print("             `omMMMMMMNy/`  `sNMMMMMMdyMN/d+MMMMMMMMMMMMom+NMsyMMMMMMMy.  `:smMMMMMMNs.             ")
print("o/`             /dMMMMMMMMdosdNMMMMMMMhhMN/-MMMMMMMMMMMM:+MMysMMMMMMMMdy+hMMMMMMMMm+`            `:o")
print("+MNy:`            -yMMMMMMMMMNhyymMMMMMhdMM-MMMMMMMMMMMM/MMhoMMMMMNhyhmMMMMMMMMMd/             :yNMo")
print(" yMMMNy:            .sNMMMMMMMMMM+MMMMMMymM:MMMMMMMMMMMMoMd+MMMMMMoNMMMMMMMMMMy-            :sNMMMh ")
print(" `mMMMMMNs:           .smMMMMMMMMsdMMMMMMsMshhhhhhhhhhhhyMomMMMMMNsMMMMMMMMNs-           -smMMMMMN. ")
print("  :MMMMMMMMNs-       :mNyshMMMMMMNoyhdNMMsMMMMMMMMMMMMMMMM+NMMmhysmMMMMMMdyyMN/       -smMMMMMMMM:  ")
print("   oMMMMMMMMMMms-   +MMMMMmsyNMMMMMMNmhyyyMMMMMMNNNNNMMMMMyyyhmNMMMMMMNhymMMMMMo   -omMMMMMMMMMMs   ")
print("    yMMMMMMMMMMMMmo:yNMMMMMMNysdMMMMMMMMMMMMMMN-     -NMMMMMMMMMMMMMmyyNMMMMMMNy:omMMMMMMMMMMMMh    ")
print("     +NMMMMMMMMMMMMMmoohMMMMMMMdsyNMMMMMMMMMMMN`     `NMMMMMMMMMMMhydMMMMMMMhoodMMMMMMMMMMMMMMo     ")
print("      -mMMMMMMMMMMMMMMMdsoMMMMMMMNyymMMMMMMMMMM`     .MMMMMMMMMNyyNMMMMMMMoodMMMMMMMMMMMMMMMm-      ")
print("       `sMMMMMMMMMMMMMMMMh+MMMMMMMMMhyhMMMMMMMM-     -MMMMMMMdyhMMMMMMMMMoyMMMMMMMMMMMMMMMMy`       ")
print("         :NMMMMMMMMMMMMMMMssMMMMMMMMMMmyyNMMMMM/     /MMMMNhymMMMMMMMMMMyoMMMMMMMMMMMMMMMN/         ")
print("          `hMMMMMMMMMMmmMMM+hMMMMMMMMMMMMhsMMMMhooooohMMMyhMMMMMMMMMMMMd+MMMmmMMMMMMMMMMh.          ")
print("            +NMMMMMMMMy `:sM/mMMMMMMMMMMMMsdMMMMMMMMMMMMNsMMMMMMMMMMMMm:Ny:` sMMMMMMMMMo            ")
print("             -dMMMMMMMd   -My+MM:/shmMMMMMN+hhhNMMMMNhhh+NMMMMMmhs/:MMosM:   hMMMMMMMm-             ")
print("              `sMMMMMMm   .Mh/MM-    `-/shmNmNmsyMMhsmNNNmhs/-`    .MM+hM-   mMMMMMMy`              ")
print("                :NMMMMM`  `Mm:MMmo.        `+dMMmosdMMm+`        .omMM/dM.  `NMMMMN/                ")
print("                 :odMMM-  `NN-MMmMMd+`        /MMMMMM+        `/hMMmMM:mM`  .MMMdo:                 ")
print("                 hNy+ommo. NN-hyhsNMMNy/:////oNMMMMMMNo//////yNMMNshyh-NN`.ommo+yNd                 ")
print("                 -NMMNs+smdMM.dMMMyhMMMMMMMMMMMMMMMMMMMMMMMMMMMMhyMMMm`NMdNs+sNMMN:                 ")
print("                  -NMMMMmsoyN.NMMMMmshMMMMmddddddddddddddmMMMMhomMMMMN.Ny+smMMMMN:                  ")
print("                   -NMMMs/hdo.mMMMMMN.ooddNMMMMMMMMMMMMMMNdds+.NMMMMMN.odh+oMMMN:                   ")
print("                    -NMMh  .M+dMMMMMM-N/MMMMMMMMMMMMMMMMMMMMoN-NMMMMMm/M-  yMMN-                    ")
print("                     -NMMh: hN+dMMMMM-N/MMMMMMMMMMMMMMMMMMMMoN-NMMMMd/mh -yMMN-                     ")
print("                      -mMMMm+mMssMMMM-N/MMMMMMMMMMMMMMMMMMMMoN-NMMMssMm+dMMMN-                      ")
print("                       .NMMMMMMMd+mMM:N/MMMMMMMMMMMMMMMMMMMMoN-NMN+dMMMMMMMN-                       ")
print("                        .mMMMMMMmNosssN/MMMMMMMyshhssMMMMMMMoNsssodMMMMMMMN-                        ")
print("                         .mMMMMM+yM+dMMhymMMMMd+MMMM/hMMMMNhhMMM/h`NMMMMMN-                         ")
print("                          .mMMMMhoModMMMMdyhMm/MNsydN:mMdydMMMMMos/MMMMMN-                          ")
print("                           .hNMMMNMs/dMMMMMmy/mN+mM+dN/ymMMMMMm+oNMMMMNh-                           ")
print("                              -/sdNy  :hMMMMMMN/NMMM/mMMMMMMd/  yNds/-                              ")
print("                                   .    -yMMMMyoMMMMyoMMMMh:    .                                   ")
print("                                          .sNMsoMMMMy+MNy-                                          ")
print("                                            `+ooMMMMy+o.                                            ")
print("                                               oMMMMs                                               ")
print("                                               .NMMM-                                               ")
print("                                                /NNo                                                ")
print("")
print("DUNDAM")
print("------")

print("                                                                                                    ")
print("                                                  ody++                                             ")
print("                                               sddNMNs +++                                          ")
print("                                             shMMMMMMMmo//o///                                      ")
print("                                           /hMMMMMNdydmdh/  +/s                                     ")
print("                                         +hNMMMMMd+ /+/       /++//                                 ")
print("                                       /oddMMMMMMNmdmNNmdh//    / ++                                ")
print("                                   ///oydNNMMMMMMMMMMMMMMMNmddho   +//                              ")
print("                              /+sosyhNNMMMMMMMMMMMMMMMMMMMNNMMhs+    ////  /                        ")
print("                          o+////sdmmmdyhNdydhhmMMMMMMMMMMh//++          ////+/                      ")
print("                        /sNyhsydydNNNmddNmmNmmNMMMMMMMMMMyydNmdmssso/+/+o   /++/                    ")
print("                    +dyymNMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMmNNNMdmho  /////                ")
print("                   +mMMMMMMMMMMMMMMMMNNMmNMmmmMMNMsmmNMNNNMdmdmNhhmmMNNMNMNddo++/o//o               ")
print("                  /dMMMMMMMMMNNdmNNmNhymmdmdsdNMmMshNMMMNMmsdNMN+sNMMNNNsdmmmNmNsmddh               ")
print("                 +dMMNNNNmddNmMhhhmmNNmdmNmds+hMMdoMMMNdNmyNNMmhdMNNNddsmNhdNmsydddm+               ")
print("                 dmddhsodmhodNMNNmddNNMMNNMMmo/sNNymNhyNmyMdddmNNmmdhdhhhhhys+/ /                   ")
print("                 s/ +osyydddyhmNMMMMNNmhyhmmmd+/oNMms+ddomdossysosodyhhys+/                         ")
print("                 y     ///+osddmdNMMMMMNNddhosy  yNhsNMNNNhydhhmNNdhhsyo                            ")
print("                 o           soohhdNMNNNdNmmh+d/ /moNMMMmmmdmhhyyso/ooo/                            ")
print("          /+     o            //+ymddddddmNMdsm/  y/dmmddNdysoo+    /o                /oo           ")
print("         /oo+o/  +        /       ss+shsyhhhddm///hs+dhhms/          /  /           /shhs+          ")
print("             /            oo/     +o+o/ /yNhsom//+hdhymds             /os            +y++           ")
print("                                   //    osyMNM+/ohmohmss                                           ")
print("                                          +omNN+/oyshNyso                                           ")
print("        /             +h+/                  hmN/oshdNdy/                 /ss/            /o+        ")
print("       +o+o+            +                   /Ny+yhmNdh/                  //            +ys+o        ")
print("                                            +Nhshdmds                                               ")
print("                     o+//                   yyhNhhso                        +                       ")
print("                    /so+/                 +hdmhh ys/                       //+                      ")
print("                                         hddhdy+/+o                                    /+oo+/       ")
print("                                        om/sNyds//+/                       / /          /++o        ")
print("        so+/         +oo/               sd om+dho+++/                      +o+                      ")
print("       // /          +//                +N+hdhymy/+ o                      /                        ")
print("                                         hdNmmomh  /++                    /                         ")
print("                                         +mhhmsNy /ss/                    +o+                       ")
print("                       /s/                sydNNd/ sh/o/                    /         /oo++          ")
print("          //++/         /              /  +mhNy//oymo/++               /            /oo+s+          ")
print("          +//               //       +/yo+ddy+ /oNdyyo//+//           /os/                          ")
print("                           /o/    ///sdhhyo+/+shNMMMNmdy+//+/          //                           ")
print("                                  /hhhysssyyydMMMMmmmNMMNds+////+               /                   ")
print("                   /              +hdyhs+symhdNNMNmhhddNdddhdyodh/              +s+                 ")
print("                 ss+              oymNmdhdmMNmMmNNmhyhdNmhhoydmmds               ys+                ")
print("                +o/               o/+mNNMmmMMmMNMNNMMMMNNNmNNMNNmo                                  ")
print("                                  / /yNNNmmmMNNNNmNMMMMNNNNNmNNNs       /                           ")
print("                         /s//       +hhNMmdmmmmNmmMMMMMMMNNMmMNds       oy/                         ")
print("                        ++yo+        o oddNMmNNMNMNNNNNmMMmyyho//       /+s                         ")
print("                         /o         +   ohNNmdMMmMNNMMNNmh/   +os                                   ")
print("                                  soy   /ssMNNmmmNNNNdy+/      sh+                                  ")
print("                                  sy     + hmNNMNNMm+           +o                                  ")
print("                                           + shmhys                                                 ")
print("                                                                                                    ")